"""Boundary cases and rejection of malformed inputs in blockchainkit.crypto."""

from dataclasses import replace

import pytest

import blockchainkit as bk
from blockchainkit.crypto import is_prime


@pytest.mark.parametrize("field", ["a", "b"])
def test_curve_coefficients_must_be_reduced(field):
    with pytest.raises(ValueError, match="reduced modulo"):
        replace(bk.crypto.TOY_CURVE, **{field: 17})


@pytest.mark.parametrize("generator", [None, (0, 0)])
def test_curve_requires_finite_on_curve_generator(generator):
    with pytest.raises(ValueError, match="finite point"):
        replace(bk.crypto.TOY_CURVE, generator=generator)


@pytest.mark.parametrize("scalar,point", [(True, (5, 1)), (1.5, (5, 1)), (1, (0, 0))])
def test_multiplication_rejects_invalid_scalar_or_point(scalar, point):
    with pytest.raises(ValueError, match="integer scalar and an on-curve point"):
        bk.crypto.multiply(scalar, point, bk.crypto.TOY_CURVE)


def test_prime_that_divides_a_miller_rabin_base():
    # 73 is prime and divides the fixed witness 28178; a zero witness must
    # be skipped rather than incorrectly classifying this prime as composite.
    assert 28178 % 73 == 0
    assert is_prime(73)
    assert not is_prime(73 * 73)


def test_challenge_requires_bytes():
    point = bk.crypto.TOY_CURVE.generator
    with pytest.raises(TypeError, match="message must be bytes"):
        bk.crypto.challenge("message", point, point, bk.crypto.TOY_CURVE)


@pytest.mark.parametrize("bad_point", [None, (0, 0)])
@pytest.mark.parametrize("position", [0, 1])
def test_transcript_rejects_infinite_or_off_curve_points(bad_point, position):
    curve = bk.crypto.TOY_CURVE
    points = [curve.generator, curve.generator]
    points[position] = bad_point
    assert not bk.crypto.verify_transcript(*points, 0, 1, curve)


@pytest.mark.parametrize("position", [0, 1])
def test_transcript_rejects_points_outside_generator_subgroup(position):
    # y² = x³ + 1 modulo 7 has a subgroup of order 3 generated by (0, 1),
    # while (3, 0) has order 2. On-curve validation alone is insufficient.
    curve = bk.crypto.Curve(7, 0, 1, (0, 1), 3)
    outsider = (3, 0)
    assert curve.contains(outsider)
    assert bk.crypto.multiply(2, outsider, curve) is None
    points = [curve.generator, curve.generator]
    assert bk.crypto.verify_transcript(*points, 0, 1, curve)
    points[position] = outsider
    assert not bk.crypto.verify_transcript(*points, 0, 1, curve)


@pytest.mark.parametrize("position", range(4))
def test_nonce_recovery_rejects_out_of_range_responses_and_challenges(position):
    curve = bk.crypto.TOY_CURVE
    scalars = [1, 2, 3, 4]
    scalars[position] = curve.order
    first = bk.crypto.SchnorrSignature(curve.generator, scalars[0])
    second = bk.crypto.SchnorrSignature(curve.generator, scalars[1])
    with pytest.raises(ValueError, match="scalar must be below order"):
        bk.crypto.recover_reused_nonce_key(first, second, *scalars[2:], order=curve.order)


def test_singular_curve_is_rejected_before_group_operations():
    with pytest.raises(ValueError, match="singular curve"):
        bk.crypto.Curve(17, 0, 0, (1, 1), 19)


@pytest.mark.parametrize("field", ["p", "order"])
def test_curve_rejects_composite_field_or_subgroup_order(field):
    with pytest.raises(ValueError, match="must be prime"):
        replace(bk.crypto.TOY_CURVE, **{field: 15})
